Controllers/DomainsController.cs
using dns_network_programming.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Net.Sockets;
using System.Net;
using System.Text;
using Microsoft.CodeAnalysis;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Xml.Linq;

namespace dns_network_programming.Controllers
{
    public class DomainsController : Controller
    {
        [HttpGet]
        public IActionResult Index() => View();
        #region AddressRecord
        [HttpGet]
        public IActionResult AddressRecord() => View();
        [HttpPost]
        public IActionResult AddressRecord(AddressVM model)
        {
            byte[] DNSQuery;
            byte[] DNSReply;
            UdpClient dnsClient = new UdpClient(model.Domain, 53);
            DNSQuery = makeQuery(DateTime.Now.Millisecond * 60, model.Domain);
            dnsClient.Send(DNSQuery, DNSQuery.GetLength(0)); IPEndPoint remoteEP = new IPEndPoint(IPAddress.Any, 0); DNSReply = dnsClient.Receive(ref remoteEP);
            model.IpAddress = ParseDnsResponse(DNSReply,model.Domain);
            IPHostEntry hostEntry = Dns.GetHostEntry(model.Domain);
            model.HostName = hostEntry.HostName;
            return View(model);
        }
        #endregion
        [HttpGet]
        public IActionResult NameServerRecord() => View();
        [HttpGet]
        public IActionResult CanonicalNameRecord() => View();
        [HttpGet]
        #region MailExchangeRecord
        public IActionResult MailExchangeRecord() => View();
        [HttpPost]
        public IActionResult MailExchangeRecord(DomainVM model)
        {
            byte[] DNSQuery;
            byte[] DNSReply;
            UdpClient dnsClient = new UdpClient(model.IPAdress, 53);
            DNSQuery = makeQuery(DateTime.Now.Millisecond * 60, model.Domain);
            dnsClient.Send(DNSQuery, DNSQuery.GetLength(0)); IPEndPoint endpoint = null; DNSReply = dnsClient.Receive(ref endpoint);
            model.NameServer = makeResponse(DNSReply, model.Domain);
            return View(model);
        }
        #endregion
        public byte[] makeQuery(int id, string name)
        {
            byte[] data = new byte[512];
            byte[] Query;
            data[0] = (byte)(id >> 8); data[1] = (byte)(id & 0xFF);
            data[2] = (byte)1; data[3] = (byte)0;
            data[4] = (byte)0; data[5] = (byte)1;

            data[6] = (byte)0; data[7] = (byte)0;
            data[8] = (byte)0; data[9] = (byte)0; data[10] = (byte)0; data[11] = (byte)0;
            string[] tokens = name.Split(new char[] { '.' }); string label;
            int position = 12;
            for (int j = 0; j < tokens.Length; j++)
            {
                label = tokens[j];
                data[position++] = (byte)(label.Length & 0xFF);
                byte[] b = System.Text.Encoding.ASCII.GetBytes(label); for (int k = 0; k < b.Length; k++)
                {
                    data[position++] = b[k];
                }
            }
            data[position++] = (byte)0; data[position++] = (byte)0; data[position++] = (byte)15; data[position++] = (byte)0; data[position++] = (byte)1;
            Query = new byte[position + 1]; for (int i = 0; i <= position; i++)
            {
                Query[i] = data[i];
            }
            return Query;
        }
        public string makeResponse(byte[] data, string name)
        {
            int qCount = ((data[4] & 0xFF) << 8) | (data[5] & 0xFF); int aCount = ((data[6] & 0xFF) << 8) | (data[7] & 0xFF);
            int position = 12;
            for (int i = 0; i < qCount; ++i)
            {
                name = "";
                position = proc(position, data, ref name); position += 4;
            }
            string Response = "";
            for (int i = 0; i < aCount; ++i)
            {
                name = "";
                position = proc(position, data, ref name); position += 12;
                name = "";
                position = proc(position, data, ref name); Response += name + "\r\n";
            }
            return Response;
        }
        private int proc(int position, byte[] data, ref string name)
        {
            int len = (data[position++] & 0xFF);
            if (len == 0)
            {
                return position;
            }
            int offset;

            do
            {
                if ((len & 0xC0) == 0xC0)
                {
                    if (position >= data.GetLength(0))
                    {
                        return -1;
                    }
                    offset = ((len & 0x3F) << 8) | (data[position++] & 0xFF);
                    proc(offset, data, ref name); return position;
                }
                else
                {
                    if ((position + len) > data.GetLength(0))
                    {
                        return -1;
                    }
                    name += Encoding.ASCII.GetString(data, position, len); position += len;
                }
                if (position > data.GetLength(0))
                {
                    return -1;
                }
                len = data[position++] & 0xFF; if (len != 0)
                {
                    name += ".";
                }
            }
            while (len != 0); return position;
        }
        public string ParseDnsResponse(byte[] data,string name)
        {
            {
                int qCount = ((data[4] & 0xFF) << 8) | (data[5] & 0xFF);
                int aCount = ((data[6] & 0xFF) << 8) | (data[7] & 0xFF);
                int position = 12;
                for (int i = 0; i < qCount; ++i)
                {
                    name = "";
                    position = proc(position, data, ref name);
                    position += 4;
                }
                StringBuilder responseBuilder = new StringBuilder();
                for (int i = 0; i < aCount; ++i)
                {
                    name = ""; position = proc(position, data, ref name);
                    position += 12;
                    string ipAddress = $"{data[position++]}.{data[position++]}.{data[position++]}.{data[position++]}";
                    responseBuilder.AppendLine($"{ipAddress}");
                }
                return responseBuilder.ToString();
            }
        }
    }
}

Views/Domains/AddressRecord.cshtml
@{
    ViewData["Title"] = "Address Record";
}
@model dns_network_programming.ViewModel.AddressVM
@* ************** Content ************** *@
<div class="row g-6">
    <div class="col-md-12">
        <div class="card mb-6">
            <h5 class="card-header">Address Record</h5>
            <div class="card-body demo-vertical-spacing demo-only-element">
                <form asp-action="AddressRecord" asp-controller="Domains">
                    
                    <div class="row mb-6">
                        <label asp-for="@Model.Domain" class="col-sm-3 col-form-label" class="mb-0 "></label>
                        <div class="col-sm-10">
                            <input asp-for="@Model.Domain" type="text" class="form-control" placeholder="viettechgroup.vn" />
                        </div>
                    </div>

                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Seacrh</button>
                        </div>
                    </div>
                </form>

                <div class="row">
                    <div class="mb-0">
                        <label asp-for="@Model.IpAddress" class="mb-0"></label>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <textarea readonly>
                            @{
                                if (Model != null && !string.IsNullOrEmpty(Model.IpAddress))
                                {
                                    @Model.IpAddress
                                }
                            }
                                  </textarea>

                    </div>
                </div>
                <div class="row">
                    <div class="mb-0">
                        <label asp-for="@Model.HostName" class="mb-0"></label>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <textarea readonly>
                            @{
                                if (Model != null && !string.IsNullOrEmpty(Model.HostName))
                                {
                                    @Model.HostName
                                }
                            }
                                  </textarea>

                    </div>
                </div>
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon11">&#64;</span>
                    <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon11" />
                </div>

                <div class="form-password-toggle">
                    <label class="form-label" for="basic-default-password12">Password</label>
                    <div class="input-group">
                        <input type="password" class="form-control" id="basic-default-password12" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" aria-describedby="basic-default-password2" />
                        <span id="basic-default-password2" class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                    </div>
                </div>

                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon13" />
                    <span class="input-group-text" id="basic-addon13">&#64;example.com</span>
                </div>

                <div class="input-group">
                    <span class="input-group-text" id="basic-addon14">https://example.com/users/</span>
                    <input type="text" class="form-control" placeholder="URL" id="basic-url1" aria-describedby="basic-addon14" />
                </div>

                <div class="input-group">
                    <span class="input-group-text">With textarea</span>
                    <textarea class="form-control" aria-label="With textarea" placeholder="Comment"></textarea>
                </div>

            </div>
        </div>
    </div>
</div>

Views/Domains/CanonicalNameRecord.cshtml
@{
    ViewData["Title"] = "Canonical Name Record";
}

@* ************** Content ************** *@
<div class="row g-6">
    <div class="col-md-12">
        <div class="card mb-6">
            <h5 class="card-header">Canonical Name Record</h5>
            <div class="card-body demo-vertical-spacing demo-only-element">

                <div class="input-group">
                    <span class="input-group-text" id="basic-addon11">&#64;</span>
                    <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon11" />
                </div>

                <div class="form-password-toggle">
                    <label class="form-label" for="basic-default-password12">Password</label>
                    <div class="input-group">
                        <input type="password" class="form-control" id="basic-default-password12" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" aria-describedby="basic-default-password2" />
                        <span id="basic-default-password2" class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                    </div>
                </div>

                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon13" />
                    <span class="input-group-text" id="basic-addon13">&#64;example.com</span>
                </div>

                <div class="input-group">
                    <span class="input-group-text" id="basic-addon14">https://example.com/users/</span>
                    <input type="text" class="form-control" placeholder="URL" id="basic-url1" aria-describedby="basic-addon14" />
                </div>

                <div class="input-group">
                    <span class="input-group-text">With textarea</span>
                    <textarea class="form-control" aria-label="With textarea" placeholder="Comment"></textarea>
                </div>

            </div>
        </div>
    </div>
</div>

Views/Domains/Index.cshtml
@{
    ViewData["Title"] = "Domain";
}

@* ************** Content ************** *@
<div class="row">
    <!-- Order Statistics -->
    <div class="col-md-12 col-lg-12 col-xl-12 order-0 mb-6">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div class="card-title mb-0">
                    <h5 class="mb-1 me-2">Order Statistics</h5>
                    <p>Lam vao day</p>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Domains/MailExchangeRecord.cshtml
@{
    ViewData["Title"] = "Mail Exchange Record";
}
@model dns_network_programming.ViewModel.DomainVM
@* ************** Content ************** *@
<div class="row g-6">
    <div class="col-md-12">
        <div class="card mb-6">
            <h5 class="card-header">Mail Exchange Record</h5>
            <div class="card-body demo-vertical-spacing demo-only-element">
                <form asp-action="MailExchangeRecord" asp-controller="Domains">
                    <div class="row mb-6">
                        <label asp-for="@Model.IPAdress" class="col-sm-3 col-form-label" class="mb-0"></label>
                        <div class="col-sm-10">
                            <input asp-for="@Model.IPAdress" type="text" class="form-control" placeholder="11.22.33.44" />
                        </div>
                    </div>
                    <div class="row mb-6">
                        <label asp-for="@Model.Domain" class="col-sm-3 col-form-label" class="mb-0 "></label>
                        <div class="col-sm-10">
                            <input asp-for="@Model.Domain" type="text" class="form-control" placeholder="viettechgroup.vn" />
                        </div>
                    </div>
                   
                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Seacrh</button>
                        </div>
                    </div>
                </form>

                <div class="row">
                    <div class="mb-0">
                        <label asp-for="@Model.NameServer" class="mb-0"></label>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <textarea readonly>
                            @{
                                if (Model != null && !string.IsNullOrEmpty(Model.NameServer))
                                {
                                    @Model.NameServer
                                }
                            }
                                  </textarea>

                    </div>
                </div>
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon11">&#64;</span>
                    <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon11" />
                </div>

                <div class="form-password-toggle">
                    <label class="form-label" for="basic-default-password12">Password</label>
                    <div class="input-group">
                        <input type="password" class="form-control" id="basic-default-password12" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" aria-describedby="basic-default-password2" />
                        <span id="basic-default-password2" class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                    </div>
                </div>

                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon13" />
                    <span class="input-group-text" id="basic-addon13">&#64;example.com</span>
                </div>

                <div class="input-group">
                    <span class="input-group-text" id="basic-addon14">https://example.com/users/</span>
                    <input type="text" class="form-control" placeholder="URL" id="basic-url1" aria-describedby="basic-addon14" />
                </div>

                <div class="input-group">
                    <span class="input-group-text">With textarea</span>
                    <textarea class="form-control" aria-label="With textarea" placeholder="Comment"></textarea>
                </div>

            </div>
        </div>
    </div>
</div>

Views/Domains/NameServerRecord.cshtml
@{
    ViewData["Title"] = "Name Server Record";
}

@* ************** Content ************** *@
<div class="row g-6">
    <div class="col-md-12">
        <div class="card mb-6">
            <h5 class="card-header">Name Server Record</h5>
            <div class="card-body demo-vertical-spacing demo-only-element">

                <div class="input-group">
                    <span class="input-group-text" id="basic-addon11">&#64;</span>
                    <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon11" />
                </div>

                <div class="form-password-toggle">
                    <label class="form-label" for="basic-default-password12">Password</label>
                    <div class="input-group">
                        <input type="password" class="form-control" id="basic-default-password12" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" aria-describedby="basic-default-password2" />
                        <span id="basic-default-password2" class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                    </div>
                </div>

                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon13" />
                    <span class="input-group-text" id="basic-addon13">&#64;example.com</span>
                </div>

                <div class="input-group">
                    <span class="input-group-text" id="basic-addon14">https://example.com/users/</span>
                    <input type="text" class="form-control" placeholder="URL" id="basic-url1" aria-describedby="basic-addon14" />
                </div>

                <div class="input-group">
                    <span class="input-group-text">With textarea</span>
                    <textarea class="form-control" aria-label="With textarea" placeholder="Comment"></textarea>
                </div>

            </div>
        </div>
    </div>
</div>